version: '3.8'

services:

  command:
    build:
      context: .
      target: command
    image: robot-vacuums

  tests:
    build:
      context: .
      target: tests
    image:
      robot-vacuums-tests
